#!/usr/bin/env python3
from pyrsistent import PMap

from src.lib.game.discrete_soccer import Action
from ...lib.game import Agent, RandomAgent, GameState


class MinimaxAgent(RandomAgent):
    """An agent that makes decisions using the Minimax algorithm, using a
    evaluation function to approximately guess how good certain states
    are when looking far into the future.

    :param evaluation_function: The function used to make evaluate a
        GameState. Should have the parameters (state, player_id) where
        `state` is the GameState and `player_id` is the ID of the
        player to calculate the expected payoff for.

    :param alpha_beta_pruning: True if you would like to use
        alpha-beta pruning.

    :param max_depth: The maximum depth to search using the minimax
        algorithm, before using estimates generated by the evaluation
        function.
    """
    def __init__(self, evaluate_function, alpha_beta_pruning=False, max_depth=5):
        super().__init__()
        self.evaluate = evaluate_function
        self.alpha_beta_pruning = alpha_beta_pruning
        self.max_depth = max_depth

    def decide(self, state: GameState):
        # TODO: Implement this agent!
        #
        # Read the documentation in /src/lib/game/_game.py for
        # information on what the decide function does.
        #
        # Do NOT call the soccer evaluation function that you write
        # directly from this function! Instead, use
        # `self.evaluate`. It will behave identically, but will be
        # able to work for multiple games.
        #
        # Do NOT call any SoccerState-specific functions! Assume that
        # you can only see the functions provided in the GameState
        # class.
        #
        # If you would like to see some example agents, check out
        # `/src/lib/game/_agents.py`.

        if not self.alpha_beta_pruning:
            return self.minimax(state)
        else:
            return self.minimax_with_ab_pruning(state)

    def minimax(self, state: GameState):
        # This is the suggested method you use to do minimax.  Assume
        # `state` is the current state, `player` is the player that
        # the agent is representing (NOT the current player in
        # `state`!)  and `depth` is the current depth of recursion.
        #return super().decide(state)
        if state.actions
        for index, action in enumerate(state.actions):
            if index == 0:
                best_action = action
                best_score = self.min_value(state.act(action))
            else:
                score = self.min_value(state.act(action))
                if score > best_score:
                    best_action = action
                    best_score = score
        return best_action



        return

    def minimax_with_ab_pruning(self, state, player, depth=1,
                                alpha=float('inf'), beta=-float('inf')):
        return super().decide(state)

    def min_value(self, state: GameState, depth: int = 1):
        # If at a terminal state, return the reward
        if state.is_terminal:
            return state.reward(state.current_player)
        # If we reached the max search depth, return the utility
        if depth >= self.max_depth:
            return self.evaluate(state, state.current_player)

        for index, action in state.actions:
            if index = 0:
                smallest_score = self.max_value(state.act(action), depth)



    def max_value(self, state: GameState, depth: int = 1):
